### ISSUE TITLE
Como desenvolvedor, gostaria de uma conta no firebase configurada e vinculada ao client da extensão do chrome.

### ISSUE THREAD

**Issue by afonsopacifer** [brainsticker/brainsticker#5]
- [x] Estudar o firebase.
- [x] Criar um conta.
- [ ] Conectar com o client ([vuefire](https://github.com/vuejs/vuefire))

**Comment by manzettidenis** [comment]
Quebrei a issue em outra menor:
https://github.com/brainsticker/brainsticker/issues/12
